---
title: "Souverains"

format:
  ofce-html:
    code-fold: true
    code-summary: "code"
    code-tools: false
    code-block-border-left: true
    code-block-bg: "#EEEEEE"
echo: true
freeze: false
---

```{r, include = FALSE, cache = FALSE}
ofce::init_qmd(echo=TRUE)
tsh <- source_data("souverains/taux_souverains_historiques.R", 
                                           lapse = "day",
                                           metadata = TRUE)

ratings <- source_data("souverains/ratings", 
                            lapse = "month")
```

```{r}
#| label: fig-spreads
#| fig-cap: Taux souverains France, Allemagne, *spread* France-Allemagne

data_graph <- tsh |> 
  pluck("data") |> 
  filter(date >= "1995-01-01") |> 
  distinct(date, pays, .keep_all = TRUE) |> 
  mutate( 
    date  = if_else(date < floor_date(now(), "month") - months(1), floor_date(date, unit = "month") + days(15), date) ) |>
  mutate(
    geo = case_match(pays,
                     "france" ~ "FR",
                     "germany" ~ "DE",
                     "italy" ~ "IT")) |> 
  group_by(date, geo, pays) |> 
  summarize(taux = mean(taux, na.rm = TRUE),
            freq = if_else(n()>1, "monthly", "daily"),
            .groups = "drop") |>
  complete(date, geo) |>  
  group_by(date) |> 
  mutate(spread = taux - taux[geo=="DE"]) |> 
  ungroup() |> 
  mutate(
    tooltip = glue(
      "<b>{pays}</b>
      {ifelse(freq=='monthly', date_mois(date), date_jour(date))}
      taux: {round(taux,2)}%
      écart avec Allemagne: {round(spread,2)}%")) 

gtaux <-  ggplot(data_graph) +
  aes(x=date, y=taux, color=geo, group=geo) +
  geom_line(aes(linewidth = freq), show.legend = FALSE) +
  geom_point_interactive(
    aes(tooltip = tooltip, data_id = date, fill = geo, size = freq),
    col = "white", shape=21, stroke = 0.1,
    hover_nearest = TRUE) +
  scale_size_manual(values = c(daily = 0.25, monthly = 1)) +
  scale_linewidth_manual(values = c(daily = 0.25, monthly = 0.5)) +
  labs(y="Taux (en %)",
    x = NULL,
    fill=NULL)+
  scale_y_continuous(limits = c(0, 5))+
  ofce::scale_color_pays("eurostat") +
  ofce::scale_ofce_date(
    date_breaks = "2 year", 
    date_minor_breaks = "1 month",
    limits = c(ymd("2024-01-01"), NA)) +
   guides(
     linewidth = "none",
     size = "none",
     fill = marquee::guide_marquee(
     "!!1, !!2, !!3")) 

gspread <-  ggplot(data_graph |> filter(geo != "DE")) +
  aes(x=date, y=spread, color=geo, group=geo) +
  geom_line(aes(linewidth = freq), show.legend = FALSE) +
  geom_point_interactive(
    aes(tooltip = tooltip, data_id = date, fill = geo, size = freq),
    col = "white", shape=21, stroke = 0.1,
    hover_nearest = TRUE) +
  scale_size_manual(values = c(daily = 0.25, monthly = 1)) +
  scale_linewidth_manual(values = c(daily = 0.25, monthly = 0.5)) +
  geom_smooth(method = "lm",
              formula = y ~1, 
              linewidth = 0.1,
              alpha = 0.1,
              fill=NA, show.legend = FALSE) +
  labs(y="Spread (en %)",
    x = NULL,
    fill=NULL)+
  scale_y_continuous(limits = c(0, 2),
                     breaks = 0:2)+
  ofce::scale_color_pays("eurostat") +
  ofce::scale_ofce_date(
    date_breaks = "2 year", 
    date_minor_breaks = "1 month",
    limits = c(ymd("2024-01-01"), NA)) +
   guides(
     linewidth = "none",
     size = "none",
     fill = marquee::guide_marquee(
     "!!1, !!2")) +
  ofce_caption(
    source="investing.com",
    note = "données téléchargées le {date_jour(tsh$date)}",
    dpt = data_graph$date, dptf = "day")
library(patchwork)
gg <- wrap_plots(gtaux,gspread,ncol=1, axes = "collect_x", heights = c(5,2))
girafy(gg, 1.3)
```

```{r}
#| label: tbl-notations-taux
#| tbl-cap: "Taux souverains et Notations souveraines"

library(countrycode)
country_codes <- codelist|>
  select(country = country.name.en, country.name.fr, country_code_2 = genc2c)

ratings |>
  left_join(country_codes, by = "country")|>
  select(-country)|>
  select(country_code_2, country = country.name.fr, everything())|>
  arrange(-TE, `10Y`)|>
  select(-TE)|>
  filter(!is.na(country))|>
  gt()|>
    tab_options(
      quarto.disable_processing = TRUE,
      table.font.size = 12
    ) |> 
  cols_align(
    align = "center",
    columns = -c(country))|>
  cols_label(
    country = "",
    country_code_2 = ""
    )|>
  tab_source_note(source_note = "Source: investing.com, tradingeconomics.com. Calculs OFCE.")|>
  fmt_number(
    dec_mark = ",",
    sep_mark = ".",
    decimals = 2
  ) |>
  fmt_flag(columns = country_code_2) |>
  sub_missing(
    missing_text = ""
  )|>
  opt_interactive(
    use_search = TRUE,
    use_filters = TRUE,
    use_resizers = TRUE,
    use_highlight = TRUE,
    use_compact_mode = TRUE,
    use_text_wrapping = FALSE,
    use_page_size_select = TRUE
  )
```
